services:
  - type: web
    name: precaorama-frontend
    runtime: node
    buildCommand: bun install && ./node_modules/.bin/vinxi build
    startCommand: node .output/server/index.mjs
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: VITE_API_URL
        sync: false   # preencha manualmente no painel do Render
    autoDeploy: true
